.TH transflac 1
.SH NAME
transflac \- convert FLAC audio files to lossy formats.
.SH SYNOPSIS
.B transflac
[input_FLAC_directory] [output_lossy_directory] [lossy_format] [codec_quality]
.SH DESCRIPTION
The process of converting FLAC files to lossy formats
and preserving tag information can be a bit tedious.
.BR transflac
is designed to automate this. It will start at the input_flac_directory and
recursively walk the directory structure converting each flac audio file to the
specified lossy codec - preserving all associated tag information.  Additionally,
any cover art (stored in the directory structure as 
albumart | cover | folder . gif | jpg | jpeg | png | tiff) will be
duplicated in the target lossy directories.
.SH CONFIGURATION
\fBtransflac\fR allows for customization of certain items in the configuration.
.PP
If you wish to change an option in the configuration, first create a copy: \ficp /etc/transflac.conf $HOME/.transflac.conf\fR then modify only the \fI$HOME/.transflac.conf\fR version.
.PP
The configuration variables cn be set as follows:
.TP
.B VARIABLE="value"
"value" needs to be quoted.
.TP
All shell escaping/quoting rules apply.
.TP
Here is a list of options \fBtransflac\fR recognizes:
.TP
.B FIGFONT="small"
Default setting is small.
This is the font to be used by the Figlet generated banner.
.TP
.B input_flac_dir=""
Specifies the directory starting point which will be recursively
search for FLAC audio files.  All FLAC audio files in the directory
structure will be converted to the specified lossy codec.
Default value is "$1" which is arg1 from the command line invocation.
This value is case sensitive.  Any symlinks that are encountered will be
resolved and the physical path will be displayed.
.TP
.B output_lossy_dir=""
Specifies the target directory which will be used to store the lossy
audio files which are created during the conversion process.
Default value is "$2" which is arg2 from the command line invocation.
This value is case sensitive.  Any symlinks that are encounted will be
resolved and the physical path will be displayed.
.TP
.B lossy_codec=""
Specifies the lossy codec which will be used to convert the FLAC
audio files.  Default value is "$3" which is arg3 from the command line
invocation.  This value is NOT case sensitive.
OPUS generally will provide the best sound quality for a given filesize
or bitrate - and is the recommended codec.
.br
Valid values are: OPUS | OGG | AAC | MP3
.TP
.B codec_quality=""
Specifies the quality preset which will be used to encode the lossy
audio files.  Default value is "$4" which is arg4 from the command line
invocation.  This value is NOT case sensitive.
OPUS STANDARD quality provides Full bandwidth stereo music,
good quality approaching transparency - and is the recommended
setting.
.br
Valid values are: LOW | MEDIUM | STANDARD | HIGH | PREMIUM
.TS
allbox,tab(@);
c c c c c c
l r r r r r .
CODEC@LOW@MEDIUM@STANDARD@HIGH@PREMIUM
OPUS@48 kbps@64 kbps@96 kbps@128 kbps@192 kbps
OGG@80 kbps@96 kbps@112 kbps@128 kbps@160 kbps
AAC@40 kbps@80 kbps@96 kbps@128 kbps@224 kbps
MP3@85 kbps@100 kbps@115 kbps@130 kbps@165 kbps
.TE
.SH EXAMPLES
Possible ways one can call \fBtransflac\fR:
.TP
.B transflac
"You will be prompted to enter all options.  If you have customized
options in $HOME/.transflac.conf those values will be substituted.
.TP
.B transflac [input_flac_dir] [output_lossy_dir] [lossy_codec] [codec_quality]
transflac processing will proceed with the options entered on the
command line.
.SH BACKEND TOOLS
\fBtransflac\fR requires the following backend tools to work:
.TP
.B *
opus-tools - Required to convert files to the OPUS lossy format
.TP
.B *
vorbis-tools - Required to convert files to the OGG Vorbis lossy
format
.TP
.B *
ffmpeg - Required to convert files to the AAC or MP3 lossy formats
.TP
.B *
flac - Required to convert files from the FLAC lossless format
.TP
.B *
rsync - Required to copy cover art files to the new lossy format
directory structure
.TP
.B *
figlet - Required to facilate display formatting
.SH "SEE ALSO"
.BR opusenc (1),
.BR oggenc (1),
.BR flac (1),
.BR ffmpeg (1)
.SH AUTHOR
Gerald Cox <gbcox@fedoraproject.org>
.SH WWW
.BR https://bitbucket.org/gbcox/transflac/
